MYB-408: Adding Flurry
devspark-com/mybus-ios pull request #146
Opened 2016-12-06 12:25 UTC by ignaciodevspark

Adding Flurry as a second analytics tracking tool https://devspark-com.atlassian.net/browse/MYB-408

2016-12-06 14:18 UTC, lisandro commented
LGTM 👍

2016-12-06 15:14 UTC, marcosjvivar requested changes

2016-12-06 15:14 UTC, marcosjvivar commented on MyBus/Podfile.lock
> +COCOAPODS: 1.0.1
We will have conflicts when using the updated version of CocoaPods in #145 
Is this pod available in CocoaPods 1.1.1???

2016-12-06 15:59 UTC, safink commented on MyBus/MyBus/MainViewController.swift
> +            Flurry.logEvent("Switched to ACtiveSearch")
This should be: "Switched to Puntos de Recarga" o "Activated Puntos de Recarga"

2016-12-06 16:24 UTC, lisandro commented on MyBus/Podfile.lock
> +COCOAPODS: 1.0.1
I believe that it won't affect existing Pods. I updated in #145 only because I have installed the latest gem of CocoaPods

2016-12-06 16:25 UTC, safink commented on MyBus/MyBus/Services/MyBusService.swift
> +                Flurry.logEvent("searchRoads error \(error!.description)")
We should use "?" instead of "!" and provide a "No description available" to avoid unexpected app crashes whenever the "error" object is nil
Meaning,
Flurry.logEvent("searchRoads error \(error?.description ?? "No description available)")

2016-12-06 16:26 UTC, safink commented on MyBus/MyBus/Services/MyBusService.swift
> +                CLSLogv("getCompleteRoads error %@", getVaList([error!.description]))
Same as above

2016-12-06 16:26 UTC, safink commented on MyBus/MyBus/Services/MyBusService.swift
> +                    Flurry.logEvent("getRechargeCardPoints error \(error!.description)")
Same as above

2016-12-06 16:26 UTC, safink commented on MyBus/MyBus/Services/MyBusService.swift
> +                Flurry.logEvent("getRechargeCardPoints error \(error!.description)")
Same as above

2016-12-07 15:12 UTC, marcosjvivar approved these changes

2016-12-07 15:29 UTC, merged